/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TaskListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTaskListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTaskListGenerated.onFilterBar().iCheckFilterField({ property: "task_id" });
            Then.onTheTaskListGenerated.onFilterBar().iCheckFilterField({ property: "status" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheTaskListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheTaskListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheTaskListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheTaskListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheTaskListGenerated.onTable(defaultTableId).iPressAction("Mark Done");
            Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckAction("Mark Done", { enabled: false });
            Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"task_id":{"header":"task_id"},"description":{"header":"description"},"status":{"header":"status"},"priority":{"header":"priority"},"due_date":{"header":"due_date"},"created_at":{"header":"created_at"},"created_by":{"header":"created_by"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheTaskListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheTaskListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheTaskListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheTaskObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});