/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TaskObjectPageObjectPage journey");

        opaTest("Navigate to TaskObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheTaskListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheTaskListGenerated.onTable().iCheckRows();
            When.onTheTaskListGenerated.onTable().iPressRow(0);

            Then.onTheTaskObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheTaskObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheTaskObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheTaskObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zrc01_sd.v0001", action: "markDone", unbound: false }, { enabled: false });
            // When.onTheTaskObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zrc01_sd.v0001", action: "markDone", unbound: false });
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTaskObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "task_id" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "description" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "status" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "priority" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "due_date" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "created_at" });
            Then.onTheTaskObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "created_by" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});