CLASS zbp_i_rap03_um4 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_rap03_umtest.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS zbp_i_rap03_um4 IMPLEMENTATION.
ENDCLASS.
