CLASS zbp_i_rap02_task DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_rap02_task.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS zbp_i_rap02_task IMPLEMENTATION.
ENDCLASS.
