/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("NoteObjectPageObjectPage journey");

        opaTest("Navigate to NoteObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheNoteListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheNoteListGenerated.onTable().iCheckRows();
            When.onTheNoteListGenerated.onTable().iPressRow(0);

            Then.onTheNoteObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheNoteObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheNoteObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "note_id" });
            Then.onTheNoteObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "title" });
            Then.onTheNoteObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "content" });
            Then.onTheNoteObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "changed_at" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});